/***********************************************************************************************************************
 * Flash access helpers for the bootloader. See boot_flash.h.
 **********************************************************************************************************************/

#include "boot_flash.h"
#include "boot_layout.h"

/** Flash instance generated by the FSP configurator (r_flash_hp). */
#define BOOT_FLASH                   (g_flash0)

/** Staging buffer for flash-to-flash copies. Multiple of the 128 byte code flash write unit. */
#define BOOT_FLASH_CHUNK             (512U)

static bool    g_flash_open = false;
static uint8_t g_chunk[BOOT_FLASH_CHUNK] BSP_ALIGN_VARIABLE(4);

/***********************************************************************************************************************
 * Erase block size for the region @p address falls in.
 **********************************************************************************************************************/
static uint32_t boot_flash_block_size (uint32_t address)
{
    if (address >= BSP_FEATURE_FLASH_DATA_FLASH_START)
    {
        return BSP_FEATURE_FLASH_HP_DF_BLOCK_SIZE;
    }

    if (address < BSP_FEATURE_FLASH_HP_CF_REGION0_SIZE)
    {
        return BSP_FEATURE_FLASH_HP_CF_REGION0_BLOCK_SIZE;
    }

    return BSP_FEATURE_FLASH_HP_CF_REGION1_BLOCK_SIZE;
}

/***********************************************************************************************************************
 * Public API
 **********************************************************************************************************************/

fsp_err_t boot_flash_open (void)
{
    if (g_flash_open)
    {
        return FSP_SUCCESS;
    }

    fsp_err_t err = BOOT_FLASH.p_api->open(BOOT_FLASH.p_ctrl, BOOT_FLASH.p_cfg);

    if ((FSP_SUCCESS == err) || (FSP_ERR_ALREADY_OPEN == err))
    {
        g_flash_open = true;

        return FSP_SUCCESS;
    }

    return err;
}

void boot_flash_close (void)
{
    if (g_flash_open)
    {
        (void) BOOT_FLASH.p_api->close(BOOT_FLASH.p_ctrl);
        g_flash_open = false;
    }
}

fsp_err_t boot_flash_erase (uint32_t address, uint32_t bytes)
{
    fsp_err_t err = boot_flash_open();

    if (FSP_SUCCESS != err)
    {
        return err;
    }

    uint32_t block = boot_flash_block_size(address);

    if ((0U == block) || (0U != (bytes % block)))
    {
        return FSP_ERR_INVALID_ARGUMENT;
    }

    return BOOT_FLASH.p_api->erase(BOOT_FLASH.p_ctrl, address, bytes / block);
}

fsp_err_t boot_flash_write (uint32_t dest, const void * p_src, uint32_t bytes)
{
    fsp_err_t err = boot_flash_open();

    if (FSP_SUCCESS != err)
    {
        return err;
    }

    return BOOT_FLASH.p_api->write(BOOT_FLASH.p_ctrl, (uint32_t) p_src, dest, bytes);
}

fsp_err_t boot_flash_log_write (uint32_t address, uint32_t value)
{
    uint32_t staged = value;

    return boot_flash_write(address, &staged, BSP_FEATURE_FLASH_HP_DF_WRITE_SIZE);
}

fsp_err_t boot_flash_df_blank (uint32_t address, uint32_t bytes, bool * p_blank)
{
    *p_blank = false;

    fsp_err_t err = boot_flash_open();

    if (FSP_SUCCESS != err)
    {
        return err;
    }

    flash_result_t result = FLASH_RESULT_NOT_BLANK;

    err = BOOT_FLASH.p_api->blankCheck(BOOT_FLASH.p_ctrl, address, bytes, &result);

    if (FSP_SUCCESS == err)
    {
        *p_blank = (FLASH_RESULT_BLANK == result);
    }

    return err;
}

/***********************************************************************************************************************
 * Erases the destination and copies flash to flash one chunk at a time.
 *
 * The source is read into RAM BEFORE each program operation, so no code flash read happens while the FCU is busy.
 **********************************************************************************************************************/
fsp_err_t boot_flash_copy (uint32_t dest, uint32_t src, uint32_t bytes)
{
    fsp_err_t err = boot_flash_erase(dest, bytes);

    if (FSP_SUCCESS != err)
    {
        return err;
    }

    for (uint32_t offset = 0U; offset < bytes; offset += BOOT_FLASH_CHUNK)
    {
        uint32_t chunk = bytes - offset;

        if (chunk > BOOT_FLASH_CHUNK)
        {
            chunk = BOOT_FLASH_CHUNK;
        }

        const volatile uint8_t * p_src = (const volatile uint8_t *) (src + offset);

        for (uint32_t i = 0U; i < chunk; i++)
        {
            g_chunk[i] = p_src[i];
        }

        err = boot_flash_write(dest + offset, g_chunk, chunk);

        if (FSP_SUCCESS != err)
        {
            return err;
        }
    }

    return FSP_SUCCESS;
}

/***********************************************************************************************************************
 * CRC32, bitwise so no 1 KB table is needed in a size constrained bootloader.
 **********************************************************************************************************************/
uint32_t boot_crc32 (uint32_t address, uint32_t length)
{
    const volatile uint8_t * p_data = (const volatile uint8_t *) address;
    uint32_t                 crc    = 0xFFFFFFFFU;

    for (uint32_t i = 0U; i < length; i++)
    {
        crc ^= (uint32_t) p_data[i];

        for (uint32_t bit = 0U; bit < 8U; bit++)
        {
            uint32_t mask = (uint32_t) (-((int32_t) (crc & 1U)));
            crc = (crc >> 1) ^ (0xEDB88320U & mask);
        }
    }

    return crc ^ 0xFFFFFFFFU;
}
